server:
  port: 8080

patients:
  mock:
    url: ${GATEWAY_MOCK:http://mock:8080}

oapi:
  srv:
    patients: ${GATEWAY_PATIENTS:http://evisita-oapisrvpatients:8080/patients/v1}
    companions: ${GATEWAY_COMPANIONS:http://evisita-oapisrvcompanions:8080/companions/v1}