server:
  port: 8082

patients:
  mock:
    url: ${GATEWAY_MOCK:http://localhost:8198}

oapi:
  srv:
    patients: ${GATEWAY_PATIENTS:http://localhost:8080/patients/v1}
    companions: ${GATEWAY_COMPANIONS:http://localhost:8081/companions/v1}